apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-platform-copilot.fullname" . }}-ui
spec:
  selector:
    app: {{ include "data-platform-copilot.fullname" . }}-ui
  ports:
    - name: http
      port: 8501
      targetPort: 8501
