apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-platform-copilot.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: data-platform-copilot
  template:
    metadata:
      labels:
        app: data-platform-copilot
    spec:
      containers:
        - name: copilot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8001
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
