apiVersion: v1
kind: Service
metadata:
  name: data-platform-copilot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
  selector:
    app: data-platform-copilot
